### ISSUE TITLE
BFC（块级格式化上下文）

### ISSUE THREAD

**Issue by huxiaosheng** [huxiaosheng/huxiaosheng.github.io#1]
## 为什么要清除浮动

> 一个块级元素的高度如果没有设置height，那么其高度就是由里面的元素来撑开的，如果子元素使用浮动，脱离了标准的文档流，那么父元素的高度会将其忽略。
    

```css
/*简洁版*/
.clearfix:before, .clearfix:after {
	content:"";
	display:table;
}
.clearfix:after{
	clear:both;
	overflow:hidden;
}
.clearfix{
    zoom:1;
}

/* 经典版 */
.clearfix:after {
    visibility: hidden;
    display: block;
    font-size: 0;
    content: " ";
    clear: both;
    height: 0;
}
```
